{
    "name": "Tag_Whatsapp_18",
    "version": "1.0.0",
    "category": "Tools",
    "summary": "Send WhatsApp via WasenderAPI",
    "author": "Tag Technology",
    "depends": [
        "base",
        "mail",
        "sale",
        "account",
        "point_of_sale",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/stock_alert_cron.xml",
        "data/scheduled_actions.xml",
        "data/cron.xml",
        "views/adv_whatsapp_out_views.xml",
        "views/sale_order_view.xml",
        "views/purchase_order_view.xml",
        "views/stock_warehouse_view.xml",
        "views/stock_picking_view_inherit.xml",
        "views/res_config_settings_view.xml",
        "views/invoices_whatsapp_button.xml",
        "views/whatsapp_multi_recipient_wizard_view.xml",
        "views/pos_order_view.xml",
        "views/whatsapp_composer_view.xml",
    ],
    "installable": True,
    "application": True,
}