from . import whatsapp_out
from . import whatsapp_autoreply
from . import adv_whatsapp_group
from . import sale_order
from . import account_move
from . import account_payment
from . import purchase_order
from . import whatsapp_multi_recipient_wizard
from . import stock_alert
from . import res_config_settings
from . import tock_picking_receipt_whatsapp
from . import whatsapp_composer
from . import res_partner
from . import send_statement_wizard
