import ast
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def po_entries():
    text = (ROOT / 'i18n' / 'ar_001.po').read_text(encoding='utf-8')
    result = {}
    blocks = text.split('\n\n')
    for block in blocks:
        mid = re.search(r'^msgid "(.*)"$', block, re.M)
        mst = re.search(r'^msgstr "(.*)"$', block, re.M)
        if mid and mst and mid.group(1):
            result[mid.group(1)] = mst.group(1)
    return result


class V695FullLocalizationTest(unittest.TestCase):
    def test_manifest_version_is_v695(self):
        manifest = ast.literal_eval((ROOT / '__manifest__.py').read_text(encoding='utf-8'))
        self.assertEqual(manifest['version'], '18.0.6.9.5')

    def test_every_frontend_translation_literal_has_nonempty_arabic_translation(self):
        entries = po_entries()
        required = set()
        literal = re.compile(r'_t\(\s*(["\'])(.*?)\1\s*\)')
        tr_literal = re.compile(r'tr\(\s*(["\'])(.*?)\1\s*\)')
        for path in (ROOT / 'static' / 'src').rglob('*'):
            if path.suffix not in {'.js', '.xml'}:
                continue
            text = path.read_text(encoding='utf-8')
            required.update(match.group(2).replace("\\'", "'") for match in literal.finditer(text))
            required.update(match.group(2).replace("\\'", "'").replace('&amp;', '&') for match in tr_literal.finditer(text))
        missing = sorted(label for label in required if not entries.get(label, '').strip())
        self.assertEqual(missing, [], msg=f'Missing Arabic frontend translations: {missing}')

    def test_report_exports_are_localized_and_support_rtl(self):
        source = (ROOT / 'controllers' / 'reports.py').read_text(encoding='utf-8')
        self.assertIn('request.env._', source)
        self.assertIn('right_to_left()', source)
        self.assertIn("_is_arabic", source)
        for translated_call in (
            "tr('Generated By')", "tr('Generated At')", "tr('Applied Filters')",
            "tr('Executive Summary')", "tr('Revenue & Payments')", "tr('Wash Operations')",
            "tr('Service Performance')", "tr('Station Performance')", "tr('Top Customers')",
            "tr('Supplies & Exceptions')", "tr('Paid POS Orders')",
        ):
            self.assertIn(translated_call, source, msg=f'Export label is not routed through Odoo translation: {translated_call}')
        self.assertIn('dir="{direction}"', source)

    def test_backend_analytics_detail_copy_uses_odoo_translation(self):
        source = (ROOT / 'models' / 'business_analytics.py').read_text(encoding='utf-8')
        translated_literals = (
            "_('Customer classification for the selected analytics period.')",
            "_('Customer mix for the selected analytics period.')",
            "_('Monthly revenue for this service category.')",
            "_('Wash Order Activity')",
            "_('Analytics Detail')",
            "_('No drill-down is available for this item.')",
            "_('Not found')",
        )
        for wrapped in translated_literals:
            self.assertIn(wrapped, source, msg=f'Backend copy is not routed through Odoo translation: {wrapped}')

    def test_every_backend_translation_literal_has_nonempty_arabic_translation(self):
        entries = po_entries()
        required = set()
        for folder in ('models', 'controllers'):
            for path in (ROOT / folder).rglob('*.py'):
                tree = ast.parse(path.read_text(encoding='utf-8'))
                for node in ast.walk(tree):
                    if not isinstance(node, ast.Call) or not node.args:
                        continue
                    first = node.args[0]
                    if not isinstance(first, ast.Constant) or not isinstance(first.value, str):
                        continue
                    func = node.func
                    is_translation = isinstance(func, ast.Name) and func.id in {'_', 'tr'}
                    is_translation = is_translation or (isinstance(func, ast.Attribute) and func.attr in {'_tr', '_'})
                    if is_translation:
                        required.add(first.value)
        missing = sorted(label for label in required if not entries.get(label, '').strip())
        self.assertEqual(missing, [], msg=f'Missing Arabic backend/export translations: {missing}')

    def test_custom_odoo_views_and_field_labels_have_arabic_entries(self):
        entries = po_entries()
        required = (
            'Car Wash', 'Car Wash Dashboard', 'Dashboard', 'Station Configuration',
            'Car Wash Stations', 'Car Wash Station', 'Show on Car Wash Dashboard',
            'Include this work center as a physical car-wash station on the dashboard.',
            'Car Wash Station Type', 'Dashboard Sequence',
            'Lower numbers appear first on the car-wash dashboard.',
            'Car Wash Vehicle Size',
            'Explicit Small/Large size copied from the related car-wash sale order when available.',
            'Vehicle Type', 'Operational car-wash size used by the station dashboard.',
        )
        missing = [label for label in required if not entries.get(label, '').strip()]
        self.assertEqual(missing, [], msg=f'Missing Arabic Odoo view/field translations: {missing}')

    def test_rtl_detection_also_honors_arabic_document_language(self):
        js = (ROOT / 'static' / 'src' / 'js' / 'dashboard.js').read_text(encoding='utf-8')
        self.assertIn('getAttribute("lang")', js)
        self.assertIn('startsWith("ar")', js)

    def test_arabic_layout_contract_uses_odoo_direction(self):
        js = (ROOT / 'static' / 'src' / 'js' / 'dashboard.js').read_text(encoding='utf-8')
        xml = (ROOT / 'static' / 'src' / 'xml' / 'dashboard.xml').read_text(encoding='utf-8')
        css = (ROOT / 'static' / 'src' / 'css' / 'dashboard_concept_replica.css').read_text(encoding='utf-8')
        self.assertIn('detectRtl()', js)
        self.assertIn("t-att-dir=\"state.isRtl ? 'rtl' : 'ltr'\"", xml)
        self.assertIn('.cw-dashboard-app.is-rtl', css)


if __name__ == '__main__':
    unittest.main()
