import ast
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class V693InteractiveManagementReportsContractTest(unittest.TestCase):
    def test_manifest_version_is_v693(self):
        manifest = ast.literal_eval((ROOT / '__manifest__.py').read_text(encoding='utf-8'))
        self.assertGreaterEqual(tuple(map(int, manifest['version'].split('.'))), (18, 0, 6, 9, 3))

    def test_backend_exposes_transaction_rows_for_drilldown_and_exports(self):
        source = (ROOT / 'models/report_center.py').read_text(encoding='utf-8')
        self.assertIn("'transactions'", source)
        self.assertIn("'payment_methods'", source)
        self.assertIn("'trend_bucket_key'", source)
        self.assertIn("'product_id'", source)
        self.assertIn("'order_id'", source)
        self.assertIn("'model': 'pos.order'", source)

    def test_reports_ui_has_read_only_drilldown_contract(self):
        js = (ROOT / 'static/src/js/dashboard.js').read_text(encoding='utf-8')
        xml = (ROOT / 'static/src/xml/dashboard.xml').read_text(encoding='utf-8')
        for token in (
            'reportDetail', 'openReportDetail', 'closeReportDetail', 'reportDetailRows',
            'reportExporting', 'reportExportFormat', 'response.blob()', 'Preparing management workbook',
            '/car_wash_dashboard/reports/print?',
        ):
            self.assertIn(token, js)
        for token in (
            'cw-report-detail-panel', 'closeReportDetail', 'reportDetailRows',
            "openReportDetail('kpi'", "openReportDetail('revenue_bucket'",
            "openReportDetail('service'", "openReportDetail('payment_method'",
        ):
            self.assertIn(token, xml)

    def test_clean_print_route_exists_and_print_does_not_use_browser_page_print(self):
        controller = (ROOT / 'controllers/reports.py').read_text(encoding='utf-8')
        js = (ROOT / 'static/src/js/dashboard.js').read_text(encoding='utf-8')
        self.assertIn('/car_wash_dashboard/reports/print', controller)
        self.assertIn('window.print()', controller)
        self.assertNotIn('window.print();', js)

    def test_excel_is_management_workbook_with_full_sections(self):
        source = (ROOT / 'controllers/reports.py').read_text(encoding='utf-8')
        for sheet_name in (
            'Executive Summary', 'Operations', 'Revenue & Payments', 'Services',
            'Stations', 'Customers', 'Supplies', 'Exceptions',
        ):
            self.assertIn(sheet_name, source)
        for token in (
            'freeze_panes', 'autofilter', 'conditional_format', 'add_chart',
            'Crystal Clean - Management Report', 'Generated By', 'Applied Filters',
        ):
            self.assertIn(token, source)

    def test_pdf_is_multi_section_paginated_management_report(self):
        source = (ROOT / 'controllers/reports.py').read_text(encoding='utf-8')
        self.assertNotIn("data['operations'][:35]", source)
        for token in (
            'Executive Summary', 'Revenue & Payments', 'Wash Operations',
            'Station Performance', 'Top Customers', 'Supplies & Exceptions',
            'PageBreak', "tr('Page')", 'Crystal Clean',
        ):
            self.assertIn(token, source)

    def test_export_feedback_and_disable_state_are_visible(self):
        xml = (ROOT / 'static/src/xml/dashboard.xml').read_text(encoding='utf-8')
        self.assertIn('state.reportExporting', xml)
        self.assertIn('reportExportFormat', xml)
        self.assertIn('Preparing', xml)


if __name__ == '__main__':
    unittest.main()
